name: 'attributions'
version: '1.0.0'
config-version: 2

profile: 'attributions'

model-paths: ["models"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  attributions:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  attribution_window_days: 30
  min_pathway_conversions: 2
